#not sure of the name of the objects

# World Capitals
Card.create! [{ :question => 'Afghanistan', :answer => 'Kabul'},
               { :question => 'Argentina', :answer => 'Buenos Aires'},
               { :question => 'Australia', :answer => 'Canberra'},
               { :question => 'Austria', :answer => 'Vienna'},
               { :question => 'Bangladesh', :answer => 'Dhaka'},
               { :question => 'Belgium', :answer => 'Brussels'},
               { :question => 'Belgium', :answer => 'Brussels'},
               { :question => 'Bulgaria', :answer => 'Sofia'},
               { :question => 'Canada', :answer => 'Ottawa'},
               { :question => 'Chile', :answer => 'Santiago'},
               { :question => 'Costa Rica', :answer => 'San Jose'},
               { :question => 'Czech Republic', :answer => 'Prague'},
               { :question => 'Cuba', :answer => 'Havana'},
               { :question => 'Denmark', :answer => 'Copenhagen'},
               { :question => 'Djibouti', :answer => 'Djibouti'},
               { :question => 'Ecuador', :answer => 'Quito'},
               { :question => 'Egypt', :answer => 'Cairo'},
               { :question => 'Estonia', :answer => 'Tallinn'},
               { :question => 'Ethiopia', :answer => 'Addis Ababa'},
               { :question => 'Finland', :answer => 'Helsinki'},
               { :question => 'France', :answer => 'Paris'},
               { :question => 'Gambia', :answer => 'Banjul'},
               { :question => 'Germany', :answer => 'Berlin'},
               { :question => 'Ghana', :answer => 'Accra'},
               { :question => 'Greece', :answer => 'Athens'},
               { :question => 'Guatemala', :answer => 'Guatemala City'},
               { :question => 'Hungary', :answer => 'Budapest'},
               { :question => 'India', :answer => 'New Delhi'},
               { :question => 'Indonesia', :answer => 'Jakarta'},
               { :question => 'Iran', :answer => 'Tehran'},
               { :question => 'Finland', :answer => 'Helsinki'},
               { :question => 'Iraq', :answer => 'Baghdad'},
               { :question => 'Ireland', :answer => 'Dublin'},
               { :question => 'Israel', :answer => 'Jerusalem'},
               { :question => 'Italy', :answer => 'Rome'},
               { :question => 'Jamaica', :answer => 'Kingson'},
               { :question => 'Japan', :answer => 'Tokyo'},
               { :question => 'Jordan', :answer => 'Amman'},
               { :question => 'Kenya', :answer => 'Nairobi'},
               { :question => 'Latvia', :answer => 'Riga'},
               { :question => 'Lebanon', :answer => 'Beirut'},
               { :question => 'Libya', :answer => 'Tripoli'},
               { :question => 'Malaysia', :answer => 'Kuala Lumpur'},
               { :question => 'Mali', :answer => 'Bamako'},
               { :question => 'Mexico', :answer => 'Mexico City'},
               { :question => 'Mongolia', :answer => 'Ulaanbaatar'},
               { :question => 'Morocco', :answer => 'Rabat'},
               { :question => 'Mozambique', :answer => 'Maputo'},
               { :question => 'Nepal', :answer => 'Kathmandu'},
               { :question => 'Nicaragua', :answer => 'Managua'},
               { :question => 'North Korea', :answer => 'Pyongyang'},
               { :question => 'Norway', :answer => 'Oslo'},
               { :question => 'Oman', :answer => 'Muscat'},
               { :question => 'Pakistan', :answer => 'Islamabad'},
               { :question => 'Peru', :answer => 'Lima'},
               { :question => 'Philippines', :answer => 'Manila'},
               { :question => 'Poland', :answer => 'Warsaw'},
               { :question => 'Qatar', :answer => 'Doha'},
               { :question => 'Romania', :answer => 'Bucharest'},
               { :question => 'Saudi Arabia', :answer => 'Riyadh'},
               { :question => 'Senegal', :answer => 'Dakar'},
               { :question => 'Sierra Leone', :answer => 'Freetown'},
               { :question => 'Slovakia', :answer => 'Bratislava'},
               { :question => 'South Korea', :answer => 'Seoul'},
               { :question => 'Spain', :answer => 'Madrid'},
               { :question => 'Sudan', :answer => 'Khartoum'},
               { :question => 'Sweden', :answer => 'Stockholm'},
               { :question => 'Switzerland', :answer => 'Bern'},
               { :question => 'Taiwan', :answer => 'Taipei'},
               { :question => 'Thailand', :answer => 'Bangkok'},
               { :question => 'Tunisia', :answer => 'Tunis'},
               { :question => 'Turkey', :answer => 'Ankara'},
               { :question => 'Uganda', :answer => 'Kampala'},
               { :question => 'Ukraine', :answer => 'Kiev'},
               { :question => 'United Arab Emriates', :answer => 'Abu Dhabi'},
               { :question => 'United Kingdom', :answer => 'London'},
               { :question => 'United States of America', :answer => 'Washington, D.C.'},
               { :question => 'Uruguay', :answer => 'Montevideo'},
               { :question => 'Uzbekistan', :answer => 'Tashkent'},
               { :question => 'Vietnam', :answer => 'Hanoi'}]

# Harry Potte Trivia

Card.create! [{:question => 'Who is Harry Potter\'s godfather?', :answer => 'Sirius Black'},
              {:question => 'Who killed Bellatrix?', :answer => 'Molly Weasley'},
              {:question => 'Who did Harry Potter marry?', :answer => 'Ginny'},
              {:question => 'Who took Hermione to the Yule Ball?', :answer => 'Viktor Krum'},
              {:question => 'At what age do you get your Hogwarts letter?', :answer => '11'},
              {:question => 'What street do the Dursley\'s live on?', :answer => ' Privet Drive'},
              {:question => 'What is Harry\'s owl\'s name?', :answer => 'Hedwig'},
              {:question => 'What is Hermione\'s cat\'s name?', :answer => 'Crookshanks'},
              {:question => 'What is Ron\'s rat named?', :answer => 'Scabbers'},
              {:question => 'What is Neville\'s toad named?', :answer => 'Trevor'},
              {:question => 'What house is Luna in?', :answer => 'Ravenclaw'},
              {:question => 'What is a non-magical person called?', :answer => 'Muggle'},
              {:question => 'Who killed Voldemort?', :answer => 'Harry Potter'},
              {:question => 'Who killed Dumbledore?', :answer => 'Severus Snape'},
              {:question => 'Who killed Severus Snape?', :answer => 'Voldemort'},
              {:question => 'What is Voldemort\'s snake named?', :answer => 'Nagini'},
              {:question => 'Who killed Sirius Black', :answer => 'Bellatrix'},
              {:question => 'What is the Weasley\'s house called?', :answer => 'The Burrow'},
              {:question => 'Who was Harry\'s first crush?', :answer => 'Cho Chang'},
              {:question => 'Who died in the Triwizard Tournament?', :answer => 'Cedric Diggory'},
              {:question => 'What is the name of Hagrid\'s dragon?', :answer => 'Norbert'},
              {:question => 'What is Voldemort\'s real name?', :answer => 'Tom Marvalo Riddle'},
              {:question => 'What is Harry\'s patronus?', :answer => 'Stag'},
              {:question => 'What is the name of the 3-headed dog?', :answer => 'Fluffy'},
              {:question => 'What spell takes away your memory?', :answer => 'Obliviate'},
              {:question => 'What is the name of Hagrid\'s spider?', :answer => 'Aragog'},
              {:question => 'What article of clothing did Harry give Dobby?', :answer => 'Sock'},
              {:question => 'What spell can unlock doors?', :answer => 'Alohomora'},
              {:question => 'Where does Harry buy his school supplies?', :answer => 'Diagon Alley'}]